### ISSUE TITLE
    raise RuntimeError( RuntimeError: server crashed for some reason, unable to proceed

### ISSUE THREAD

**Issue by sevenandseven** [liangwq/deepspeedmii_chatglm_qwen#2]

**Comment by sevenandseven** [comment]
> 你好，我根据您说的步骤执行代码，但是出现了以下错误，请问怎么解决？
> 
> Traceback (most recent call last): File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/media/deepspeedmii_chatglm_qwen/DeepSpeed-MII0/mii/launch/multi_gpu_server.py", line 105, in main() File "/media/deepspeedmii_chatglm_qwen/DeepSpeed-MII0/mii/launch/multi_gpu_server.py", line 98, in main inference_pipeline = async_pipeline(args.model_config) File "/media/deepspeedmii_chatglm_qwen/DeepSpeed-MII0/mii/api.py", line 167, in async_pipeline inference_engine = load_model(model_config) File "/media/deepspeedmii_chatglm_qwen/DeepSpeed-MII0/mii/modeling/models.py", line 14, in load_model init_distributed(model_config) File "/media/deepspeedmii_chatglm_qwen/DeepSpeed-MII0/mii/utils.py", line 187, in init_distributed deepspeed.init_distributed(dist_backend="nccl", timeout=timedelta(seconds=1e9)) File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 670, in init_distributed cdb = TorchBackend(dist_backend, timeout, init_method, rank, world_size) File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 112, in **init** self.init_process_group(backend, timeout, init_method, rank, world_size) File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 142, in init_process_group torch.distributed.init_process_group(backend, File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 900, in init_process_group store, rank, world_size = next(rendezvous_iterator) File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 245, in _env_rendezvous_handler store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout) File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 176, in _create_c10d_store return TCPStore( RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).
> 
> Traceback (most recent call last): File "/media/ai/HDD/Teamwork/wangenzhi/deepspeedmii_chatglm_qwen/chatglm_test_sever.py", line 23, in client = mii.serve( File "/media/ai/HDD/Teamwork/wangenzhi/deepspeedmii_chatglm_qwen/DeepSpeed-MII0/mii/api.py", line 124, in serve import_score_file(mii_config.deployment_name, DeploymentType.LOCAL).init() File "/tmp/mii_cache/mistral-deployment1/score.py", line 33, in init mii.backend.MIIServer(mii_config) File "/media/ai/HDD/Teamwork/wangenzhi/deepspeedmii_chatglm_qwen/DeepSpeed-MII0/mii/backend/server.py", line 47, in **init** self._wait_until_server_is_live(processes, File "/media/ai/HDD/Teamwork/wangenzhi/deepspeedmii_chatglm_qwen/DeepSpeed-MII0/mii/backend/server.py", line 62, in _wait_until_server_is_live raise RuntimeError( RuntimeError: server crashed for some reason, unable to proceed
> 
> 我改变端口号也没办法解决这个我问题，请问我该怎么办？
